---
  # tasks file for pyhuectinstall
  # It currently installs the program under the directory /home/username/ which is quite dirty. 
  # Perhaps I'll create a better folder for it in the future.
  # Most likely I wont' as it works just fine for me.
  # Call me lazy...

  - name: Create pyhuect target directory
    become: true
    become_user: "{{ user }}"
    file: 
      path: "/home/{{ user }}/test"
      state: directory
      mode: '0644'
      recurse: 'yes'


  - name: Create the color temperature schema file
    become: true
    become_user: "{{ user }}"
    copy:
      dest: ~/.hue/colortempschema.json
      mode: 0777
      owner: "{{ user.name }}"
      content: |
        {
            "schema":[
                {"hour":0, "ct": 447},
                {"hour":1, "ct": 447},
                {"hour":2, "ct": 447},
                {"hour":3, "ct": 447},
                {"hour":4, "ct": 447},
                {"hour":5, "ct": 300},
                {"hour":6, "ct": 300},
                {"hour":7, "ct": 300},
                {"hour":8, "ct": 233},
                {"hour":9, "ct": 233},
                {"hour":10, "ct": 233},
                {"hour":11, "ct": 233},
                {"hour":12, "ct": 233},
                {"hour":13, "ct": 233},
                {"hour":14, "ct": 233},
                {"hour":15, "ct": 233},
                {"hour":16, "ct": 363},
                {"hour":17, "ct": 363},
                {"hour":18, "ct": 363},
                {"hour":19, "ct": 363},
                {"hour":20, "ct": 447},
                {"hour":21, "ct": 447},
                {"hour":22, "ct": 447},
                {"hour":23, "ct": 447}
            ]
        }

  - name: Git checkout pyhuect
    become: true
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: git@github.com:robertreems/pyhuect.git
      dest: "/home/{{ user }}/pyhuect/"
    notify: (re)start the pyhuect.service

  - name: Set Systemctl service file
    become: true
    ansible.builtin.template:
      src: ./templates/pyhuect.service.j2
      dest: /etc/systemd/system/pyhuect.service
    notify: Reload the systemd daemon
